services:
  - type: worker
    name: ai-trainer
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 train-and-generate.py"
    autoDeploy: true
