services:
  - type: web
    name: ai-trainer
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "cd AIServer;python3 -m gunicorn AIServer.asgi:application -k uvicorn.workers.UvicornWorker"
    autoDeploy: true
