services:
  - type: web
    name: ai-trainer
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "python3 -m gunicorn MyFirstProject.asgi:application -k uvicorn.workers.UvicornWorker"
    autoDeploy: true
